/**
 * COLLECTOR'S EXCHANGE — Pokémon Card Catalogue Importer
 * ───────────────────────────────────────────────────────
 * Reads all Pokémon JSON files from your local machine.
 *
 * Run:    node import_cards.js
 * Output: cards_catalogue.sql  → paste into Supabase SQL Editor
 */

import fs from "fs";
import path from "path";

const CONFIG = {
  pokemon_dir:       "C:\\Users\\andre\\Downloads\\pokemon-tcg-data-master\\pokemon-tcg-data-master\\cards\\en",
  raw_conditions:    ["NM", "LP", "MP", "HP", "DMG"],
  psa_grades:        [10, 9, 8, 7, 6, 5, 4, 3, 2, 1],
  pokemon_languages: ["English", "Japanese"],
  output_file:       "cards_catalogue.sql",
  start_id:          200,
};

function esc(s) {
  if (s === null || s === undefined) return "NULL";
  return `'${String(s).replace(/'/g, "''")}'`;
}

function makeRow(id, o) {
  return `(${id},${esc(o.name)},${esc(o.setName)},${esc(o.setCode)},${esc(o.setNumber)},${esc(o.condition)},${esc(o.language)},${esc(o.rarity)},${esc(o.game)},${esc(o.imgUrl)},${esc(o.apiId)},NULL)`;
}

function allConditions() {
  return [...CONFIG.raw_conditions, ...CONFIG.psa_grades.map(g => `PSA ${g}`)];
}

function buildRows() {
  const conds = allConditions();
  const rows  = [];
  let id      = CONFIG.start_id;

  // Read every .json file in the directory
  const files = fs.readdirSync(CONFIG.pokemon_dir)
    .filter(f => f.endsWith(".json"))
    .sort();

  console.log(`  Found ${files.length} set files\n`);

  for (const file of files) {
    const setId   = file.replace(".json", "");
    const filePath = path.join(CONFIG.pokemon_dir, file);
    const cards   = JSON.parse(fs.readFileSync(filePath, "utf8"));
    console.log(`  ${setId.padEnd(12)} ${cards.length} cards  →  ${cards.length * conds.length * CONFIG.pokemon_languages.length} rows`);

    for (const card of cards) {
      for (const lang of CONFIG.pokemon_languages) {
        const imgUrl = lang === "English"
          ? (card.images?.large || card.images?.small || null)
          : null;

        for (const cond of conds) {
          rows.push(makeRow(id++, {
            name:      card.name,
            setName:   card.set?.name || setId,
            setCode:   setId,
            setNumber: card.number,
            rarity:    card.rarity || "Common",
            game:      "Pokémon",
            imgUrl,
            language:  lang,
            condition: cond,
            apiId:     `${card.id}-${cond}-${lang}`,
          }));
        }
      }
    }
  }

  return rows;
}

const SCHEMA = `
-- ════════════════════════════════════════════════════════
-- COLLECTOR'S EXCHANGE — Pokémon Card Catalogue
-- Generated by import_cards.js — safe to re-run
-- ════════════════════════════════════════════════════════

ALTER TABLE cards ADD COLUMN IF NOT EXISTS set_code   TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS set_number TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS api_id     TEXT;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cards_api_id_key') THEN
    ALTER TABLE cards ADD CONSTRAINT cards_api_id_key UNIQUE (api_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_cards_game     ON cards(game);
CREATE INDEX IF NOT EXISTS idx_cards_set_name ON cards(set_name);
CREATE INDEX IF NOT EXISTS idx_cards_set_code ON cards(set_code);
CREATE INDEX IF NOT EXISTS idx_cards_api_id   ON cards(api_id);

-- Remove old placeholder rows
DELETE FROM cards WHERE id < 200;

`;

function main() {
  const conds = allConditions();
  console.log("🃏  Collector's Exchange — Pokémon Catalogue Importer");
  console.log("──────────────────────────────────────────────────────");
  console.log(`Conditions per card: ${conds.length}  (${CONFIG.raw_conditions.join(", ")}, PSA 1–10)`);
  console.log(`Languages:           ${CONFIG.pokemon_languages.join(", ")}`);
  console.log(`Reading from:        ${CONFIG.pokemon_dir}\n`);

  const rows = buildRows();
  console.log(`\n📊 Total rows: ${rows.length.toLocaleString()}`);

  let sql = SCHEMA;
  const CHUNK = 500;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const chunk = rows.slice(i, i + CHUNK);
    sql += `\nINSERT INTO cards (id,name,set_name,set_code,set_number,condition,language,rarity,game,img_url,api_id,base_price) VALUES\n`;
    sql += chunk.join(",\n");
    sql += `\nON CONFLICT (api_id) DO UPDATE SET img_url=EXCLUDED.img_url, rarity=EXCLUDED.rarity, name=EXCLUDED.name;\n`;
  }

  fs.writeFileSync(CONFIG.output_file, sql, "utf8");
  const mb = (Buffer.byteLength(sql, "utf8") / 1024 / 1024).toFixed(1);

  console.log(`✅ Written: ${CONFIG.output_file} (${mb} MB)`);
  console.log("\nNext steps:");
  console.log("  1. Open Supabase SQL Editor");
  console.log("  2. Paste cards_catalogue.sql and run");
  console.log("  3. If it times out, split at the INSERT boundaries and run in parts");
}

main();
