
-- ════════════════════════════════════════════════════════
-- COLLECTOR'S EXCHANGE — Pokémon Card Catalogue
-- Generated by import_cards.js — safe to re-run
-- ════════════════════════════════════════════════════════

ALTER TABLE cards ADD COLUMN IF NOT EXISTS set_code   TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS set_number TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS api_id     TEXT;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cards_api_id_key') THEN
    ALTER TABLE cards ADD CONSTRAINT cards_api_id_key UNIQUE (api_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_cards_game     ON cards(game);
CREATE INDEX IF NOT EXISTS idx_cards_set_name ON cards(set_name);
CREATE INDEX IF NOT EXISTS idx_cards_set_code ON cards(set_code);
CREATE INDEX IF NOT EXISTS idx_cards_api_id   ON cards(api_id);

-- Remove old placeholder rows
DELETE FROM cards WHERE id < 200;

